openapi: "3.0.3"
info:
  title: STD23028 - TD1
  version: "1.0.0"
servers:
  - url: https://localhost:8080/STD23028/abega
paths:
  /customers:
    get:
      parameters:
        - in: query
          name: page
          required: true
          schema:
            type: integer
        - in: query
          name: pageSize
          required: true
          schema:
            type: integer
      summary: get all customers
      tags:
        - Customers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customers'
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Customers"
      
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Customers"
    put:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/CustomersWithId"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CustomersWithId"


components:
  schemas:
    Customers:
      type: object
      properties:
        name:
          type: string
          example: Razafindratelo Abegà
        age:
          type: integer
          format: int32
          example: 19
    CustomersWithId:
      allOf:
        - $ref: "#/components/schemas/Customers"
        - type: object
          properties:
            id:
              type: string
              example: "id1"
          required:
            - id



