openapi: "3.0.3"
info:
  title: API TD5 - STD23028
  version: "1.0.0"
servers:
  - url: https://localhost:8080/std23028
paths:
  /customers/:
    patch:
      tags:
        - Customers
      summary: Partially update a customer
      operationId: partiallyUpdateCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                idCustomer:
                  type: string
                  example: "cUsT-120d-df8x"
                name:
                  type: string
                  example: Razafindratelo Abegà
                age:
                  type: integer
                  format: int32
                  example: 19
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "../td1_2/td1.yaml/#/components/schemas/CustomersWithId"
    
