openapi: "3.0.3"
info:
  title: API TD4 - STD23028
  version: "1.0.0"
servers:
  - url: https://localhost:8080/std23028
paths:
  /customers/{customerId}/orders:
    get:
      tags:
        - Order
      summary: Get customer's orders
      operationId: getOrderByCustomerId
      parameters:
        - $ref: "#/components/parameters/CustomerId"
      responses:
        '200':
          description: Orders of a client with id 'customerId'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrdersWithCustomerId"
    post:
      tags:
        - Order
      summary: Create an order
      operationId: createOrderOfAClient
      parameters:
        - $ref: "#/components/parameters/CustomerId"
      requestBody:
        description: The order(s) to be create
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Orders"
      responses:
        '201':
          description: The created order
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrdersWithCustomerId"
    put:
      tags:
        - Order
      summary: update order(s)
      operationId: getOrderByCustomerId
      parameters:
        - $ref: "#/components/parameters/CustomerId"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Orders"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OrdersWithCustomerId"


components:
  parameters:
    CustomerId:
      in: path
      name: customerId
      required: true
      schema:
        type: string
        example: "cUsT-120d-df8x"
  schemas:
    MealWithQuantity:
      type: object
      properties:
        meal:
          $ref: "../td3/td3.yaml/#/components/schemas/Meal"
        quantity:
          type: integer
          format: int64
          example: 5
    Orders:
      type: object
      properties:
        reference:
          type: string
          example: "oRdEr_ref-125d-dd8f"
        meals:
          type: array
          items:
            $ref: "#/components/schemas/MealWithQuantity"
          description: List of meals with quantities ordered
        orderDateTime:
          type: string
          format: date-time
    OrdersWithCustomerId:
      type: object
      allOf:
        - $ref: "../td1_2/td1.yaml/#/components/schemas/CustomerId"
        - $ref: "#/components/schemas/Orders"
